<?php

namespace ContainerPYWgv6m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_VFPpsTOService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.vFPpsTO' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.vFPpsTO'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'step' => ['privates', '.errored..service_locator.vFPpsTO.App\\Entity\\Step', NULL, 'Cannot autowire service ".service_locator.vFPpsTO": it needs an instance of "App\\Entity\\Step" but this type has been excluded in "config/services.yaml".'],
        ], [
            'step' => 'App\\Entity\\Step',
        ]);
    }
}
