<?php

namespace ContainerPYWgv6m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0EhAcWqService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0EhAcWq' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0EhAcWq'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'boardRepository' => ['privates', 'App\\Repository\\BoardRepository', 'getBoardRepositoryService', true],
        ], [
            'boardRepository' => 'App\\Repository\\BoardRepository',
        ]);
    }
}
