<?php

namespace ContainerPYWgv6m;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getStepService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored..service_locator.4sSJBxJ.App\Entity\Step' shared service.
     *
     * @return \App\Entity\Step
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot autowire service ".service_locator.4sSJBxJ": it needs an instance of "App\\Entity\\Step" but this type has been excluded in "config/services.yaml".');
    }
}
