<?php

namespace ContainerKz3kGTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_Ci19IIService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator._ci19II' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator._ci19II'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'board' => ['privates', '.errored..service_locator._ci19II.App\\Entity\\Board', NULL, 'Cannot autowire service ".service_locator._ci19II": it needs an instance of "App\\Entity\\Board" but this type has been excluded in "config/services.yaml".'],
        ], [
            'board' => 'App\\Entity\\Board',
        ]);
    }
}
