<?php

namespace ContainerKz3kGTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_4sSJBxJService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.4sSJBxJ' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.4sSJBxJ'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'entityManager' => ['services', 'doctrine.orm.default_entity_manager', 'getDoctrine_Orm_DefaultEntityManagerService', false],
            'step' => ['privates', '.errored..service_locator.4sSJBxJ.App\\Entity\\Step', NULL, 'Cannot autowire service ".service_locator.4sSJBxJ": it needs an instance of "App\\Entity\\Step" but this type has been excluded in "config/services.yaml".'],
        ], [
            'entityManager' => '?',
            'step' => 'App\\Entity\\Step',
        ]);
    }
}
